# Generated by Django 4.2.4 on 2023-08-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentName',
            new_name='agencyName',
        ),
    ]
