# Generated by Django 4.2.4 on 2023-08-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentdetails', '0002_rename_departmentname_department_agencyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='agencyName',
            new_name='agency_Name',
        ),
    ]
