# Generated by Django 4.2.4 on 2023-08-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentdetails', '0003_rename_agencyname_department_agency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='agency_Name',
            new_name='Agency_Name',
        ),
    ]
