# Generated by Django 4.2.4 on 2023-08-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentdetails', '0001_initial'),
        ('agenciesdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('Employee_Id', models.IntegerField()),
                ('DOB', models.DateField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Agencyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenciesdetails.agency')),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departmentdetails.department')),
            ],
        ),
    ]
