# Generated by Django 4.2.4 on 2023-08-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Agencyname',
            new_name='AgencyName',
        ),
    ]
