# Generated by Django 4.2.4 on 2023-08-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_rename_agencyname_user_agencyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='AgencyName',
            new_name='Agency_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='DepartmentName',
            new_name='Department_Name',
        ),
    ]
